import { useQuery } from '@tanstack/react-query';
import { getSavedCaptions } from '../../api/services/save-caption';
import Loader from '../../components/common/Loader';
import CaptionItem from '../../components/common/caption-item';
import { ICaption } from '../../types/caption';

const ProfilePage = () => {
  const { data, isPending, error } = useQuery({
    queryKey: ['saved-captions'],
    queryFn: getSavedCaptions,
  });
  if (isPending)
    return (
      <div className="flex justify-center items-center h-40">
        <Loader className="border-primary h-10 w-10" />
      </div>
    );
  if (error) return <div className="text-red-500">Error: {error.message}</div>;

  if (data.data.length === 0)
    return (
      <div className="p-10">
        <h1 className="font-medium">You have no caption saved yet...</h1>
        <p className="text-sm text-secondary">
          You can save captions by clicking the save button on the caption you want to save.
        </p>
      </div>
    );

  return (
    <div className="p-10">
      <div className="mb-7">
        <h1 className="text-3xl font-semibold text-secondary mb-2">Saved Content: </h1>
        <p className="text-sm text-secondary">Here you can find all the content you have saved.</p>
      </div>
      <div>
        <div className="mb-5">
          <h2 className="text-xl font-semibold text-secondary mb-3">
            Idea generated by {data.topic}
          </h2>
          <ul className="grid grid-cols-1 md:grid-cols-2  gap-4">
            {data.data.map((item: ICaption) => (
              <CaptionItem key={item.id} data={item} />
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
};

export default ProfilePage;
